BookManagementWeb/Areas/Admin/Controllers/CompanyController.cs
using BookManager.DataAccess.Repository.IRepository;
using BookManager.Models;
using BookManager.Models.ViewModel;
using BookManager.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using System.Collections.Generic;

namespace BookManagementWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin + "," + StaticDetail.Role_Employee)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View(_unitOfWork.Company.GetAll());
        }

        public IActionResult CreateOrUpdate(int? id)
        {
            Company company = new Company();
            if (id != null && id != 0) // update
            {
                company = _unitOfWork.Company.Get(x => x.Id == id);
            }
            return View(company);

        }
        [HttpPost]
        public IActionResult CreateOrUpdate(Company company)
        {
            if (ModelState.IsValid)
            {        

                if(company.Id == 0) // Create
                {
                    _unitOfWork.Company.Add(company);
                    _unitOfWork.Save();
                    TempData["success"] = "Company add successfully";
                }else // update
                {
                    _unitOfWork.Company.Update(company);
                    _unitOfWork.Save();
                    TempData["success"] = "Company edit successfully";
                }
                return RedirectToAction("Index");
            }
            else
            {       
                TempData["error"] = "Something went wrong..";
                return View(company);
            }
        }
        #region Api Method
        
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> listCompany = _unitOfWork.Company.GetAll().ToList();
            return Json(new {data = listCompany});
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Company? company = _unitOfWork.Company.Get(x => x.Id == id);

            if (company != null)
            {
                _unitOfWork.Company.Remove(company);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Delete Succesful" });
            }
            else
            {
                return Json(new { success = false, message = "Delete Fail" });
            }
        }

        #endregion

    }
}

BookManagementWeb/Areas/Admin/Controllers/UserController.cs
using BookManager.DataAccess.Data;
using BookManager.DataAccess.Repository.IRepository;
using BookManager.Models;
using BookManager.Models.ViewModel;
using BookManager.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using System.Collections.Generic;

namespace BookManagementWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        [BindProperty]
        public RoleManagerVM RoleManager { get; set; }

        public UserController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var listUserFromDB = _db.ApplicationUsers.Include(x => x.Company).ToList();

            foreach (var user in listUserFromDB)
            {
                string? roleID = _db.UserRoles.FirstOrDefault(x => x.UserId == user.Id)?.RoleId;
                string? roleName = _db.Roles.FirstOrDefault(x => x.Id == roleID)?.Name;

                if (!String.IsNullOrEmpty(roleName))
                {
                    user.Role = roleName;
                }
            }
            return View(listUserFromDB);
        }

        public IActionResult Pemission(string id)
        {
            string roleID = _db.UserRoles.FirstOrDefault(x => x.UserId == id).RoleId;
            RoleManager = new()
            {
                ApplicationUser = _db.ApplicationUsers.Include(x => x.Company).FirstOrDefault(x => x.Id == id),
                RoleList = _db.Roles.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Name
                }),
                CompanyList = _db.Companies.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };

            RoleManager.ApplicationUser.Role = _db.Roles.FirstOrDefault(x => x.Id == roleID).Name;
            return View(RoleManager);
        }

        [HttpPost]
        public IActionResult Pemission()
        {
            string roleID = _db.UserRoles.FirstOrDefault(x => x.UserId == RoleManager.ApplicationUser.Id).RoleId;
            string oldRole = _db.Roles.FirstOrDefault(x => x.Id == roleID).Name;
            var applicationUser = _db.ApplicationUsers.FirstOrDefault(x => x.Id == RoleManager.ApplicationUser.Id);

            // Update happening
            if (RoleManager.ApplicationUser.Role != oldRole)
            {
                if (RoleManager.ApplicationUser.Role == StaticDetail.Role_Company)
                {
                    applicationUser.CompanyID = RoleManager.ApplicationUser.CompanyID;
                }
                //if old role == role Company -> new role not be company
                if (oldRole == StaticDetail.Role_Company)
                {
                    applicationUser.CompanyID = null;
                }

                _db.Update(applicationUser);
                _db.SaveChanges();

                // Update UserRole table
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, RoleManager.ApplicationUser.Role).GetAwaiter().GetResult();

                TempData["success"] = "Update Pemission Successfully.";
                return RedirectToAction(nameof(Pemission), new { id = RoleManager.ApplicationUser.Id });
            }
            else
            {
                // If user only change the company && and the change not equal to old company
                if (oldRole == StaticDetail.Role_Company && applicationUser.CompanyID != RoleManager.ApplicationUser.CompanyID)
                {
                    applicationUser.CompanyID = RoleManager.ApplicationUser.CompanyID;
                    _db.ApplicationUsers.Update(applicationUser);
                    _db.SaveChanges();
                    TempData["success"] = "Update Pemission Successfully.";
                    return RedirectToAction(nameof(Pemission), new { id = RoleManager.ApplicationUser.Id });
                }else
                {
                    TempData["success"] = "Update pemission successfully, but nothing to change.";
                    return RedirectToAction(nameof(Pemission), new { id = RoleManager.ApplicationUser.Id });
                }
            }

            TempData["error"] = "Update Pemission Fail.";
            return RedirectToAction(nameof(Pemission), new {id = RoleManager.ApplicationUser.Id});
        }

        #region Api Method

        [HttpPost]
        public IActionResult LockUnlockUser(string id)
        {
            var userFromDB = _db.ApplicationUsers.FirstOrDefault(x => x.Id == id);

            if (userFromDB != null)
            {
                // User is currently locked -> Unlock User
                if (userFromDB.LockoutEnd != null && userFromDB.LockoutEnd > DateTime.Now)
                {
                    userFromDB.LockoutEnd = DateTime.Now;
                    _db.Update(userFromDB);
                    _db.SaveChanges();
                    TempData["success"] = "Unlocking User Successfully.";
                    return Json(new { success = true });

                }
                else
                {
                    // User is currently unlocked -> Lock User
                    userFromDB.LockoutEnd = DateTime.Now.AddYears(1000);
                    _db.Update(userFromDB);
                    _db.SaveChanges();
                    TempData["success"] = "locking User Successfully.";
                    return Json(new { success = true });
                }
            }
            // running here means bug
            TempData["error"] = "Error while Locking/Unlocking User.";
            return Json(new { success = false });
        }
        #endregion

    }
}

BookManagementWeb/Controllers/CategoryController.cs
using BookManager.DataAccess.Data;
using BookManager.DataAccess.Repository.IRepository;
using BookManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookManagementWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View(_unitOfWork.Category.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {   
            if(category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name không được trùng với Display Order");
            }
            if(ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category add successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int id)
        {
            Category? category = _unitOfWork.Category.Get(x => x.CategoryId == id);
            if(category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name không được trùng với Display Order");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category edit successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int id)
        {
            Category? category = _unitOfWork.Category.Get(x => x.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            Category? category = _unitOfWork.Category.Get(x => x.CategoryId == id);
            if (category != null)
            {
                _unitOfWork.Category.Remove(category);
                _unitOfWork.Save();
                TempData["success"] = "Category delete successfully";
                return RedirectToAction("Index");

            }else
            {
                return NotFound();
            }
        }
    }
}

BookManagementWeb/ViewComponents/ShoppingCartViewComponent.cs
using BookManager.DataAccess.Repository.IRepository;
using BookManager.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;


namespace BookManagementWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = HttpContext.User?.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId != null)
            {
                if (String.IsNullOrEmpty(HttpContext.Session.GetInt32(StaticDetail.SessionCart).ToString()))
                {
                    HttpContext.Session.SetInt32(StaticDetail.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == userId).Count());
                }
                return View(HttpContext.Session.GetInt32(StaticDetail.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }

        }
    }
}

BookManagementWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HUFBOOK - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookManagementWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.css" />
    @* jquey code css *@
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css">
    @* slick slide *@
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HUFBOOK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(StaticDetail.Role_Admin) || User.IsInRole(StaticDetail.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Manager
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="OrderStatistic" asp-action="Index">Revenue</a>
                                    </li>
                                    @if (User.IsInRole(StaticDetail.Role_Admin))
                                    {
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register User</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="PaymentGateway" asp-action="Index">Payment Type</a>
                                        </li>
                                    }
                                    @*  <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li> *@
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div style="margin-top:100px; margin-bottom:100px;">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container text-white">
            &copy; 2024 - Book Store <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* Jquery code *@
    <script src="https://code.jquery.com/ui/1.14.0/jquery-ui.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* Notification *@
    <partial name="_NotificationPartial"></partial>
    @* tiny mce *@
    <script src="https://cdn.tiny.cloud/1/mje125hw4jwx3yoyky6uxzf0bt0lxso7ge3a4da39q8kut7n/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    @* Data table - Sweart Alrte *@
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/handleDatatable.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookManagementWeb/Views/Shared/_NotificationPartial.cshtml
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script type="text/javascript">
    const toastrOptionSuccess = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    const toastrOptionError = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": true,
        "progressBar": true,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };

    function ShowSuccessToast(message) {
        toastr.options = toastrOptionSuccess;
        toastr.success(message);
    }

    function ShowErrorToast(message) {
        toastr.options = toastrOptionError;
        toastr.error(message);
    }
</script>

<!-- #region Thông Báo khi không trả về Json -->
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            ShowSuccessToast('@TempData["success"]');
        });
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        $(document).ready(function () {
            ShowErrorToast('@TempData["error"]');
        });
    </script>
}
<!-- #endregion -->